services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: vacation_app
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: vacation_nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge